version: "3"

services:
    inventory.sdp.statoil.no:
        restart: unless-stopped
        build: .
        container_name: inventory.sdp.statoil.no
        image: sdp/inventory
        volumes:
          - ./src:/app
        ports:
          - 9002:5000
        environment:
            REFRESH: 86400
            FLASK_DEBUG: 0
            PUPPETDB_API: "http://puppet.sdp.statoil.no:8080"
